### ISSUE TITLE
New Rubric Maker button

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#91]
Let's introduce a new button from the main Rubrics page entitled [`Rubric Generator`](http://www.utas.edu.au/building-elearning/resources/mylo-rubric-generator) that opens the page up in a new window. 

![image](https://user-images.githubusercontent.com/16098808/40702970-1db46ec2-6427-11e8-93c3-1bccc9e3fdc6.png)

**Comment by kloudmm** [comment]
This option should be defaulting to ON for both devs and normal use.

**Comment by kloudmm** [comment]
Remove option - I can't think of any reason why someone would want to turn it off. It's awesome.

**Comment by kloudmm** [comment]
Possibly related bug:
![image](https://user-images.githubusercontent.com/16098808/40952490-cdda99d4-68be-11e8-8f89-610f2b2b6dbd.png)

**Comment by kloudmm** [comment]
The following error appears in Options on load:

```
Error in response to storage.get: TypeError: Cannot set property 'checked' of null
    at Object.callback (chrome-extension://kpbmnapaicbmgfhafoenboodbpopdhfg/app/options.js:124:45)
    at HTMLDocument.restore_options (chrome-extension://kpbmnapaicbmgfhafoenboodbpopdhfg/app/options.js:105:22)
```

**Comment by kloudmm** [comment]
Save and Close fails with the following error:

```
Error in response to storage.get: TypeError: Cannot read property 'checked' of null
    at Object.chrome.storage.sync.get [as callback] (chrome-extension://kpbmnapaicbmgfhafoenboodbpopdhfg/app/options.js:67:65)
    at HTMLButtonElement.save_options (chrome-extension://kpbmnapaicbmgfhafoenboodbpopdhfg/app/options.js:46:22)
```

**Comment by kloudmm** [comment]
These guys need `Title` tags. 
`Import a rubric zip file created by MyLO Rubric Generator or MyLO itself`
`Open MyLO Rubric Generator in a new window`
![image](https://user-images.githubusercontent.com/16098808/40956153-1caef63c-68d2-11e8-852d-1e4e0cf9a9f2.png)
